// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa_bk9UrKM3TNCTHbLHflo3H_jVzNTW40',
    appId: '1:498510086747:web:4935239c045cb20513b57e',
    messagingSenderId: '498510086747',
    projectId: 'batov-firebase-notes',
    authDomain: 'batov-firebase-notes.firebaseapp.com',
    storageBucket: 'batov-firebase-notes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZcPcO3KSiFm6Bp5d0_uacKbnFzkzOhHo',
    appId: '1:498510086747:android:37129914223a0c2d13b57e',
    messagingSenderId: '498510086747',
    projectId: 'batov-firebase-notes',
    storageBucket: 'batov-firebase-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCXxwWSRzMLsUWiB7ezcWEWAbJBd5Lg98',
    appId: '1:498510086747:ios:4d3feb2b2535745f13b57e',
    messagingSenderId: '498510086747',
    projectId: 'batov-firebase-notes',
    storageBucket: 'batov-firebase-notes.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCXxwWSRzMLsUWiB7ezcWEWAbJBd5Lg98',
    appId: '1:498510086747:ios:4d3feb2b2535745f13b57e',
    messagingSenderId: '498510086747',
    projectId: 'batov-firebase-notes',
    storageBucket: 'batov-firebase-notes.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa_bk9UrKM3TNCTHbLHflo3H_jVzNTW40',
    appId: '1:498510086747:web:432c4c1e455613b013b57e',
    messagingSenderId: '498510086747',
    projectId: 'batov-firebase-notes',
    authDomain: 'batov-firebase-notes.firebaseapp.com',
    storageBucket: 'batov-firebase-notes.firebasestorage.app',
  );
}
